# This file was automatically generated by open_hw_platform.
# To open the vivado project generated by open_hw_platform, run the following command
# vivado -source ./openprj.tcl

source scripts/_ohp_set_params.tcl
open_project prj/prj.xpr
