# This file was automatically generated by open_hw_platform
  set orig_cwd [pwd]
  cd kv260_custom_platform
  set ::origin_dir_loc /home/xilinx/ros2_ws/src/platforms/Vitis-Tutorials/Vitis_Platform_Creation/Design_Tutorials/01-Edge-KV260/ref_files/step3_pfm_krs/platform_repo/kv260_custom_platform/export/kv260_custom_platform/hw/kv260_custom_platform/hw_platform/prj
  set ::user_project_name prj
  source /home/xilinx/ros2_ws/src/platforms/Vitis-Tutorials/Vitis_Platform_Creation/Design_Tutorials/01-Edge-KV260/ref_files/step3_pfm_krs/platform_repo/kv260_custom_platform/export/kv260_custom_platform/hw/kv260_custom_platform/hw_platform/prj/rebuild.tcl
  cd $orig_cwd
