# This file was automatically generated by open_hw_platform
  set_property board_part xilinx.com:k26c:part0:1.1 [current_project]
  lappend ip_repo_paths /home/xilinx/ros2_ws/src/platforms/Vitis-Tutorials/Vitis_Platform_Creation/Design_Tutorials/01-Edge-KV260/ref_files/step3_pfm_krs/platform_repo/kv260_custom_platform/export/kv260_custom_platform/hw/kv260_custom_platform/hw_platform/ipcache
  set_property ip_repo_paths $ip_repo_paths [current_project]
  if { [catch {update_ip_catalog} result] } {
     puts "update_ip_catalog failed: $result"
  }
  set dr_bd_file [file tail [lindex [get_files *.bd] 0]]
  config_ip_cache -export [get_ips -all -of_object [get_files $dr_bd_file]]
  open_bd_design -auto_upgrade [get_files $dr_bd_file]
